import { PrismaClient } from "../src/generated/prisma/client";
import { PrismaNeonHttp } from "@prisma/adapter-neon";
import * as dotenv from "dotenv";
dotenv.config();

const connectionString = process.env.DATABASE_URL!;
const adapter = new PrismaNeonHttp(connectionString, {});
const prisma = new PrismaClient({ adapter });

// ── Real Warehouse & Logistics Companies in UAE & Qatar ──

const warehouses = [
  // ═══════════════════════════════════════════════════════
  // DUBAI — Jebel Ali Free Zone (JAFZA)
  // ═══════════════════════════════════════════════════════
  {
    name: "Al Futtaim Logistics",
    address: "Jebel Ali Free Zone (JAFZA), Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: "JAFZA",
    phone: "+971 4 881 8288",
    email: "contact@aflogistics.com",
    website: "https://www.aflogistics.com",
    source: "nafl_directory",
    tags: ["3pl", "warehousing", "distribution"],
  },
  {
    name: "AGS Logistics",
    address: "Warehouse No MB01, Jebel Ali Free Zone North, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: "JAFZA",
    phone: "+971 4 883 1233",
    email: "info@agslog.com",
    website: "https://www.agslog.com",
    source: "nafl_directory",
    tags: ["warehousing", "logistics"],
  },
  {
    name: "ADMC Logistics",
    address: "Warehouse RA08WF01, Roundabout 08, Jebel Ali Free Zone, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: "JAFZA",
    phone: "+971 4 584 2561",
    email: "cs@admclogistics.com",
    website: "https://www.admclogistics.com",
    source: "nafl_directory",
    tags: ["warehousing", "freight"],
  },
  {
    name: "Al Rais Cargo Agencies",
    address: "Street 510A, North Jebel Ali Freezone, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: "JAFZA",
    phone: "+971 4 881 1088",
    email: "prem@alrais.com",
    website: "https://www.alraiscargo.com",
    source: "nafl_directory",
    tags: ["cargo", "warehousing", "clearing"],
  },
  {
    name: "Blue Pearl Logistics",
    address: "114, Near Dutco Group, Jebel Ali Industrial Area 1, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: "JAFZA",
    phone: "+971 4 220 7999",
    email: null,
    website: null,
    source: "yellowpages_uae",
    tags: ["freight", "logistics", "warehousing"],
  },
  {
    name: "Centre Point Logistics",
    address: "Plot S61206, Jebel Ali Free Zone South, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: "JAFZA",
    phone: "+971 4 886 4545",
    email: null,
    website: null,
    source: "yellowpages_uae",
    tags: ["warehousing", "open yard storage"],
  },
  {
    name: "Shepherd International LLC",
    address: "Building RA08FB01, Near Gate 7, Jebel Ali North, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: "JAFZA",
    phone: "+971 4 320 7687",
    email: null,
    website: null,
    source: "yellowpages_uae",
    tags: ["warehousing", "logistics"],
  },
  {
    name: "Abdul Muhsen Shipping",
    address: "Plot S10605, Jebel Ali Freezone, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: "JAFZA",
    phone: "+971 4 886 1788",
    email: "pradeep@abdulmuhsenshipping.com",
    website: "https://www.abdulmuhsenshipping.com",
    source: "nafl_directory",
    tags: ["shipping", "warehousing"],
  },
  {
    name: "ATS Shipping",
    address: "ATS Warehouse, Plot S31111, Jebel Ali Free Zone, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: "JAFZA",
    phone: "+971 4 803 8000",
    email: "info@atsworld.co",
    website: "https://www.atsworld.co",
    source: "nafl_directory",
    tags: ["shipping", "warehousing"],
  },
  {
    name: "AW Rostamani Logistics",
    address: "Plot S10607, Jebel Ali Free Zone South, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: "JAFZA",
    phone: "+971 4 811 9999",
    email: "kishore.kumar@awrostamani.com",
    website: "https://www.awrostamanilogistics.com",
    source: "nafl_directory",
    tags: ["logistics", "warehousing", "distribution"],
  },
  {
    name: "Badami Logistics",
    address: "Plot S60812, Jebel Ali Freezone South, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: "JAFZA",
    phone: "+971 4 882 4141",
    email: "info@badamilogistics.com",
    website: null,
    source: "nafl_directory",
    tags: ["logistics", "warehousing"],
  },
  {
    name: "Milaha Logistics",
    address: "Milaha Logistics City, Jebel Ali, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: "JAFZA",
    phone: "+971 4 823 8000",
    email: "dxbcrmlog@milaha.com",
    website: "https://www.milaha.com",
    source: "web",
    tags: ["logistics", "warehousing", "maritime"],
  },
  {
    name: "Access World Logistics",
    address: "Plot S30403, Street S500, Jebel Ali Free Zone, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: "JAFZA",
    phone: "+971 4 889 1111",
    email: "kishore.natarajan@accessworld.com",
    website: "https://www.accessworld.com",
    source: "nafl_directory",
    tags: ["logistics", "warehousing", "commodities"],
  },
  {
    name: "Bertling Logistics",
    address: "Office 1106, IBN Battuta Gate Office, Jebel Ali Village, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: "JAFZA",
    phone: "+971 4 446 8100",
    email: "gary.gordon@bertling.com",
    website: "https://www.bertling.com",
    source: "nafl_directory",
    tags: ["logistics", "warehousing", "project cargo"],
  },
  {
    name: "Aratrans Transport & Logistics",
    address: "Plot M00259, Street N403, Jebel Ali Free Zone North, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: "JAFZA",
    phone: "+971 4 813 7300",
    email: "viji@aratranslogistics.com",
    website: "https://www.aratranslogistics.com",
    source: "nafl_directory",
    tags: ["transport", "logistics", "warehousing"],
  },
  {
    name: "Boxcoworld FZE",
    address: "Plot S1074, Jabel Ali, near UAE Exchange Metro Station, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: "JAFZA",
    phone: "+971 4 883 9969",
    email: "nishants@boxcoworld.io",
    website: "https://www.boxcoworld.io",
    source: "nafl_directory",
    tags: ["warehousing", "fulfillment"],
  },

  // ═══════════════════════════════════════════════════════
  // DUBAI — Other Industrial Areas
  // ═══════════════════════════════════════════════════════
  {
    name: "FLG Shipping & Logistics",
    address: "Warehouse 2, 26th Street, Al Marabea Road, Al Quoz 3, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: null,
    phone: "+971 4 886 6685",
    email: null,
    website: null,
    source: "yellowpages_uae",
    tags: ["warehousing", "clearing", "transport"],
  },
  {
    name: "Green Sky Logistics Services",
    address: "Al Quoz, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: null,
    phone: "+971 58 681 9009",
    email: null,
    website: null,
    source: "yellowpages_uae",
    tags: ["warehousing", "warehouse services"],
  },
  {
    name: "Three Lines Group",
    address: "Umm Ramool, Al Rashidiya, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: null,
    phone: "+971 4 297 8604",
    email: null,
    website: null,
    source: "yellowpages_uae",
    tags: ["warehousing", "storage", "distribution"],
  },
  {
    name: "Al Naboodah Logistics",
    address: "800 E44, Dubai-Hatta Road, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: null,
    phone: "+971 4 201 9400",
    email: "krishnakumar.nair@alnaboodah.com",
    website: "https://www.alnaboodahlogistics.com",
    source: "nafl_directory",
    tags: ["logistics", "warehousing", "distribution"],
  },
  {
    name: "Aramex Emirates",
    address: "Warehouse 03, Umm Ramool, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: null,
    phone: "+971 4 870 7500",
    email: "AbdulMus@aramex.com",
    website: "https://www.aramex.com",
    source: "nafl_directory",
    tags: ["logistics", "courier", "warehousing"],
  },
  {
    name: "Al Fadhil Cargo Clearing & Forwarding",
    address: "Aden Street, Ras Al Khor Industrial Area 1, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: null,
    phone: "+971 4 333 0303",
    email: "mani@afco.ae",
    website: "https://www.afcodubai.com",
    source: "nafl_directory",
    tags: ["cargo", "clearing", "warehousing"],
  },
  {
    name: "Aeon Shipping",
    address: "Warehouse 19, Aladdin Container Company, Sana'a Road, Ras Al Khor, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: null,
    phone: "600 500 509",
    email: "info@aeon-shipping.ae",
    website: "https://www.aeon-shipping.com",
    source: "nafl_directory",
    tags: ["shipping", "warehousing"],
  },
  {
    name: "Alma Al Junaibi Forwarding & Clearing",
    address: "Warehouse 3, Opposite Al Khail Mall, Al Qouz 1, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: null,
    phone: "+971 4 379 0945",
    email: "alsahal@emirates.net.ae",
    website: null,
    source: "nafl_directory",
    tags: ["forwarding", "clearing", "warehousing"],
  },
  {
    name: "BGL Cargo Express",
    address: "Warehouse 7, 28 B Street, Al Qouz 1, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: null,
    phone: "+971 4 323 3549",
    email: "akram@bglcargo.ae",
    website: "https://www.bglcargo.ae",
    source: "nafl_directory",
    tags: ["cargo", "express", "warehousing"],
  },
  {
    name: "Unique Freight Forwarding",
    address: "Block 40, Roundabout 5, Dubai Industrial City, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: "Dubai Industrial City",
    phone: "+971 50 101 0490",
    email: null,
    website: null,
    source: "yellowpages_uae",
    tags: ["warehousing", "distribution"],
  },
  {
    name: "Al Safa Transport",
    address: "Plot 5330129, DIC-Dubai Industrial City, Roundabout 5, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: "Dubai Industrial City",
    phone: "+971 4 874 5000",
    email: "info@alsafatransport.com",
    website: "https://www.alsafatransport.com",
    source: "nafl_directory",
    tags: ["transport", "warehousing"],
  },
  {
    name: "Allied Transport",
    address: "Dubai South, DWC, Dubai, UAE",
    city: "Dubai",
    country: "UAE",
    freeZone: "Dubai South",
    phone: "+971 4 821 7777",
    email: "salma.nadeer@allied-transport.com",
    website: "https://www.allied-transport.com",
    source: "nafl_directory",
    tags: ["transport", "logistics"],
  },
  {
    name: "Bahri Logistics DWC",
    address: "Warehouse 07, Dubai South Logistics District, Freight Complex, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: "Dubai South",
    phone: "+971 4 384 0400",
    email: "sbasalom@bahri.sa",
    website: "https://www.bahrilogistics.sa",
    source: "nafl_directory",
    tags: ["logistics", "warehousing"],
  },
  {
    name: "Agility Logistics Parks",
    address: "Al Quoz Industrial Area 4, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: null,
    phone: "+971 4 282 2042",
    email: null,
    website: "https://agilitylogisticsparks.com",
    source: "web",
    tags: ["logistics parks", "warehousing"],
  },
  {
    name: "Dubai South Logistics",
    address: "Dubai South, P.O. Box 282228, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: "Dubai South",
    phone: "800-SOUTH",
    email: "info@dubaisouth.ae",
    website: "https://www.dubaisouth.ae",
    source: "web",
    tags: ["logistics", "warehousing", "free zone"],
  },
  {
    name: "AKM Shipping & Storage",
    address: "A304 A Block, Metha Plaza, Oud Mehta, Bur Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: null,
    phone: "+971 4 345 8734",
    email: "santos.govinda@akmshipping.com",
    website: "https://www.akmshipping.com",
    source: "nafl_directory",
    tags: ["shipping", "storage", "warehousing"],
  },
  {
    name: "Al Nowras Logistics Solutions",
    address: "Office 1205, 12th Floor, B2B Tower, Business Bay, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: null,
    phone: "+971 4 824 0094",
    email: "cre@alnowras.com",
    website: "https://www.alnowras.com",
    source: "nafl_directory",
    tags: ["logistics", "freight"],
  },
  {
    name: "Airlink International UAE",
    address: "Airlink Building, Airport Road, Al Garhoud, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: null,
    phone: "+971 4 282 1050",
    email: "moustafa@airlink.ae",
    website: "https://www.airlinkuae.com",
    source: "nafl_directory",
    tags: ["logistics", "freight", "warehousing", "3pl"],
  },
  {
    name: "Compass Logistics International",
    address: "Dubai, UAE",
    city: "Dubai",
    country: "UAE",
    freeZone: null,
    phone: null,
    email: null,
    website: null,
    source: "racklify",
    tags: ["logistics", "warehousing", "international"],
  },
  {
    name: "Depoter",
    address: "Dubai, UAE",
    city: "Dubai",
    country: "UAE",
    freeZone: null,
    phone: null,
    email: null,
    website: null,
    source: "racklify",
    tags: ["3pl", "ecommerce fulfillment", "warehousing"],
  },
  {
    name: "Shorages Fulfillment Centre",
    address: "Dubai, UAE",
    city: "Dubai",
    country: "UAE",
    freeZone: null,
    phone: null,
    email: null,
    website: null,
    source: "racklify",
    tags: ["ecommerce fulfillment", "warehousing"],
  },
  {
    name: "CSS eLogix",
    address: "Dubai, UAE",
    city: "Dubai",
    country: "UAE",
    freeZone: null,
    phone: null,
    email: null,
    website: null,
    source: "racklify",
    tags: ["ecommerce fulfillment", "warehousing"],
  },
  {
    name: "Merit Freight Systems",
    address: "Office 6, Opp Dubai Municipality, Karama, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: null,
    phone: "+971 4 396 4882",
    email: null,
    website: null,
    source: "yellowpages_uae",
    tags: ["freight", "warehousing", "clearing"],
  },
  {
    name: "Vertex Ventures Logistics",
    address: "Office 306, Al Attar Building, Burjman Metro Exit 3, Khalid Bin Waleed Road, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: null,
    phone: "+971 4 272 1288",
    email: null,
    website: null,
    source: "yellowpages_uae",
    tags: ["logistics", "cargo", "warehousing"],
  },
  {
    name: "Bright Way Logistic Services",
    address: "Warehouse 88, Sheikh Maktoum, Jebel Ali Industrial Area, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: "JAFZA",
    phone: "+971 52 974 5457",
    email: null,
    website: null,
    source: "yellowpages_uae",
    tags: ["freight", "logistics", "warehousing"],
  },
  {
    name: "JD Logistics",
    address: "Dubai, UAE",
    city: "Dubai",
    country: "UAE",
    freeZone: null,
    phone: null,
    email: null,
    website: "https://www.jdl.com",
    source: "racklify",
    tags: ["logistics", "ecommerce fulfillment", "warehousing"],
  },
  {
    name: "GEODIS",
    address: "Dubai, UAE",
    city: "Dubai",
    country: "UAE",
    freeZone: null,
    phone: null,
    email: null,
    website: "https://www.geodis.com",
    source: "racklify",
    tags: ["logistics", "warehousing", "supply chain"],
  },
  {
    name: "Click Express Transport & Storage",
    address: "Office 206, Lootah Building, Marrakech Street, Umm Ramool, Dubai",
    city: "Dubai",
    country: "UAE",
    freeZone: null,
    phone: "+971 4 585 9722",
    email: null,
    website: null,
    source: "yellowpages_uae",
    tags: ["transport", "storage", "warehousing"],
  },

  // ═══════════════════════════════════════════════════════
  // ABU DHABI
  // ═══════════════════════════════════════════════════════
  {
    name: "Devcon Shipping",
    address: "M-14, Mussafah, Abu Dhabi",
    city: "Abu Dhabi",
    country: "UAE",
    freeZone: null,
    phone: "+971 2 644 0117",
    email: null,
    website: null,
    source: "yellowpages_uae",
    tags: ["warehousing", "air cargo", "clearing"],
  },
  {
    name: "Brightway Shipping & Transport",
    address: "Sara Building, Electra Street, Abu Dhabi",
    city: "Abu Dhabi",
    country: "UAE",
    freeZone: null,
    phone: "+971 2 666 0613",
    email: null,
    website: null,
    source: "yellowpages_uae",
    tags: ["warehousing", "logistics", "transportation"],
  },
  {
    name: "Al Masood Freight Forwarding",
    address: "M Floor, Al Nasr Tower, Al Nasr, Abu Dhabi",
    city: "Abu Dhabi",
    country: "UAE",
    freeZone: null,
    phone: "+971 4 884 8909",
    email: "george@almasaoodlogistics.com",
    website: "https://www.almasaoodtravel.com",
    source: "nafl_directory",
    tags: ["freight", "warehousing"],
  },
  {
    name: "Al Nawras Express General Transport",
    address: "100SR60, Industrial City ICAD3, Mussaffah, Abu Dhabi",
    city: "Abu Dhabi",
    country: "UAE",
    freeZone: "KEZAD",
    phone: "+971 4 336 0030",
    email: "infonawras@nawras.ae",
    website: "https://www.nawras.ae",
    source: "nafl_directory",
    tags: ["transport", "logistics", "warehousing"],
  },
  {
    name: "ADSO LLC Abu Dhabi",
    address: "Villa 63, Al Naseer Street, Khalidiyah, Abu Dhabi",
    city: "Abu Dhabi",
    country: "UAE",
    freeZone: null,
    phone: "+971 2 667 3775",
    email: "adso@emirates.net.ae",
    website: "https://www.adso-uae.com",
    source: "nafl_directory",
    tags: ["logistics", "warehousing"],
  },
  {
    name: "Al Khalidyya International Shipping",
    address: "4th Floor, Office 402, Bin Bishr Tower, 315 Khalifa Bin Zayed St, Al Dannah, Abu Dhabi",
    city: "Abu Dhabi",
    country: "UAE",
    freeZone: null,
    phone: "+971 2 659 2000",
    email: "inquiry@kship.ae",
    website: "https://www.khalidiashipping.com",
    source: "nafl_directory",
    tags: ["shipping", "warehousing"],
  },
  {
    name: "DHL Global Forwarding KEZAD",
    address: "Khalifa Industrial Zone Abu Dhabi (KIZAD/KEZAD), Abu Dhabi",
    city: "Abu Dhabi",
    country: "UAE",
    freeZone: "KEZAD",
    phone: null,
    email: null,
    website: "https://www.dhl.com",
    source: "web",
    tags: ["logistics", "warehousing", "distribution"],
  },
  {
    name: "KEZAD Group",
    address: "Khalifa Industrial Zone Abu Dhabi, Abu Dhabi",
    city: "Abu Dhabi",
    country: "UAE",
    freeZone: "KEZAD",
    phone: "+971 2 695 2000",
    email: null,
    website: "https://www.kezadgroup.com",
    source: "web",
    tags: ["industrial zone", "warehousing", "logistics"],
  },

  // ═══════════════════════════════════════════════════════
  // SHARJAH
  // ═══════════════════════════════════════════════════════
  {
    name: "SAIF Zone Authority",
    address: "Sharjah Airport International Free Zone, Sharjah",
    city: "Sharjah",
    country: "UAE",
    freeZone: "SAIF Zone",
    phone: "+971 6 573 3333",
    email: null,
    website: "https://www.saif-zone.com",
    source: "web",
    tags: ["free zone", "warehousing"],
  },
  {
    name: "Hamriyah Free Zone Authority",
    address: "Hamriyah Free Zone, Sharjah",
    city: "Sharjah",
    country: "UAE",
    freeZone: "Hamriyah Free Zone",
    phone: "+971 6 526 3403",
    email: null,
    website: "https://hfza.ae",
    source: "web",
    tags: ["free zone", "warehousing", "industrial"],
  },
  {
    name: "ArcelorMittal Sharjah",
    address: "Hamriyah Free Zone, Sharjah",
    city: "Sharjah",
    country: "UAE",
    freeZone: "Hamriyah Free Zone",
    phone: null,
    email: null,
    website: "https://www.arcelormittal.com",
    source: "web",
    tags: ["steel", "warehousing", "industrial"],
  },
  {
    name: "Lamprell",
    address: "Hamriyah Free Zone, Sharjah",
    city: "Sharjah",
    country: "UAE",
    freeZone: "Hamriyah Free Zone",
    phone: null,
    email: null,
    website: "https://www.lamprell.com",
    source: "web",
    tags: ["engineering", "warehousing"],
  },

  // ═══════════════════════════════════════════════════════
  // QATAR — Doha & Industrial Areas
  // ═══════════════════════════════════════════════════════
  {
    name: "Gulf Warehousing Company (GWC)",
    address: "D Ring Road, Doha, Qatar",
    city: "Doha",
    country: "Qatar",
    freeZone: null,
    phone: "+974 4449 3000",
    email: "info@gwclogistics.com",
    website: "https://www.gwclogistics.com",
    source: "web",
    tags: ["logistics", "warehousing", "3pl"],
  },
  {
    name: "Milaha (Qatar)",
    address: "P.O. Box 153, Doha, Qatar",
    city: "Doha",
    country: "Qatar",
    freeZone: null,
    phone: "+974 4402 9888",
    email: null,
    website: "https://www.milaha.com",
    source: "web",
    tags: ["logistics", "maritime", "warehousing"],
  },
  {
    name: "Qatar Shipping Company",
    address: "Doha, Qatar",
    city: "Doha",
    country: "Qatar",
    freeZone: null,
    phone: "+974 4411 1188",
    email: null,
    website: null,
    source: "fiata_directory",
    tags: ["shipping", "warehousing"],
  },
  {
    name: "Qatar Logistics & Warehousing",
    address: "Ras Laffan Industrial City, Qatar",
    city: "Ras Laffan",
    country: "Qatar",
    freeZone: null,
    phone: null,
    email: "director@qtranslogistic.com",
    website: null,
    source: "fiata_directory",
    tags: ["logistics", "warehousing"],
  },
  {
    name: "Qatar Steel Company",
    address: "P.O. Box 50090, Doha, Qatar",
    city: "Doha",
    country: "Qatar",
    freeZone: null,
    phone: "+974 4 477 8416",
    email: "procurement@qatarsteel.com",
    website: "https://www.qatarsteel.com.qa",
    source: "web",
    tags: ["steel", "warehousing", "procurement"],
  },
  {
    name: "DHL Qatar",
    address: "Doha, Qatar",
    city: "Doha",
    country: "Qatar",
    freeZone: null,
    phone: null,
    email: null,
    website: "https://www.dhl.com/qa-en",
    source: "web",
    tags: ["logistics", "warehousing", "courier"],
  },
  {
    name: "CEVA Logistics Qatar",
    address: "Doha, Qatar",
    city: "Doha",
    country: "Qatar",
    freeZone: null,
    phone: null,
    email: null,
    website: "https://www.cevalogistics.com",
    source: "web",
    tags: ["logistics", "warehousing", "supply chain"],
  },
  {
    name: "Aramex Qatar",
    address: "Doha, Qatar",
    city: "Doha",
    country: "Qatar",
    freeZone: null,
    phone: null,
    email: null,
    website: "https://www.aramex.com",
    source: "web",
    tags: ["logistics", "courier", "warehousing"],
  },
  {
    name: "Doha Oasis Warehouse",
    address: "Doha Oasis, Doha, Qatar",
    city: "Doha",
    country: "Qatar",
    freeZone: null,
    phone: null,
    email: null,
    website: null,
    source: "web",
    tags: ["warehousing", "storage"],
  },
  {
    name: "Ras Laffan Industrial Warehousing",
    address: "Ras Laffan Industrial City, Qatar",
    city: "Ras Laffan",
    country: "Qatar",
    freeZone: null,
    phone: null,
    email: null,
    website: null,
    source: "web",
    tags: ["warehousing", "industrial", "oil gas"],
  },
  {
    name: "Worldwide Logistics Services",
    address: "Doha, Qatar",
    city: "Doha",
    country: "Qatar",
    freeZone: null,
    phone: "+974 7723 7988",
    email: null,
    website: null,
    source: "web",
    tags: ["logistics", "customs clearance", "warehousing"],
  },
];

// ── Message Templates ──

const templates = [
  {
    name: "Cold Outreach",
    body: "Hi {{name}},\n\nI hope this message finds you well. We help warehouse operations in {{city}} streamline their inventory management and reduce operational costs by up to 30%.\n\nWould you be open to a quick 15-minute call to see if this could benefit your operations?\n\nBest regards",
    language: "en",
  },
  {
    name: "Follow Up",
    body: "Hi {{name}},\n\nI wanted to follow up on my previous message. I understand you're busy, but I truly believe our solution could save your team significant time and money.\n\nWould next week work for a brief chat?",
    language: "en",
  },
  {
    name: "ERP Pitch",
    body: "Hi {{name}},\n\nMany warehouses in {{city}} are struggling with manual inventory tracking and disconnected systems. Our ERP solution is designed specifically for logistics and warehousing in the UAE.\n\nFeatures include:\n- Real-time inventory tracking\n- Automated reorder alerts\n- WhatsApp integration for team communication\n- Mobile app for warehouse staff\n\nCan I share a quick demo with you?",
    language: "en",
  },
  {
    name: "Value Proposition",
    body: "Hi {{name}},\n\nWe've helped warehouses in {{country}} reduce order processing time by 40% and cut inventory errors by 90%.\n\nWould you like to see how {{name}} could achieve similar results?",
    language: "en",
  },
];

async function main() {
  console.log("Seeding database with real warehouse data...\n");

  // Clear existing data
  await prisma.message.deleteMany();
  await prisma.contact.deleteMany();
  await prisma.messageTemplate.deleteMany();
  await prisma.warehouse.deleteMany();

  // Insert warehouses
  const created = await prisma.warehouse.createMany({
    data: warehouses,
    skipDuplicates: true,
  });
  console.log(`Created ${created.count} warehouses`);

  // Insert templates
  const tmplCreated = await prisma.messageTemplate.createMany({
    data: templates,
  });
  console.log(`Created ${tmplCreated.count} message templates`);

  // Summary
  const countries = await prisma.warehouse.groupBy({
    by: ["country"],
    _count: true,
  });
  console.log("\nSummary by country:");
  countries.forEach((c) => console.log(`  ${c.country}: ${c._count}`));

  const cities = await prisma.warehouse.groupBy({
    by: ["city"],
    _count: true,
    orderBy: { _count: { city: "desc" } },
  });
  console.log("\nSummary by city:");
  cities.forEach((c) => console.log(`  ${c.city}: ${c._count}`));

  const freezones = await prisma.warehouse.groupBy({
    by: ["freeZone"],
    _count: true,
    where: { freeZone: { not: null } },
    orderBy: { _count: { freeZone: "desc" } },
  });
  console.log("\nSummary by free zone:");
  freezones.forEach((f) => console.log(`  ${f.freeZone}: ${f._count}`));

  console.log("\nSeeding complete!");
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
